// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjwapulqfcsrajtohqid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqd2FwdWxxZmNzcmFqdG9ocWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODM0MDIsImV4cCI6MjA1OTg1OTQwMn0.XTKls2WuuWF2sm2lmYmYyZ6aQxLBCeUQ7YUQMZI3iHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);